### ISSUE TITLE
Backticks around code snippets

### ISSUE THREAD

**Issue by jacksorjacksor** [jacksorjacksor/BuildYourOwnDeveloperBlogWithUmbraco15AndAstro#35]
Removed: https://github.com/withastro/astro/issues/11594

Added to global.css

```css title=global.css
@layer utilities{
    /* Removes back ticks around code */
    .prose code::before,
    .prose code::after {
        content: none;
    }
    
    /* Removes speech marks around quotes */
    .prose blockquote p:first-of-type::before,
    .prose blockquote p:last-of-type::after {
        content: none;
    }
}
````
